language: python
install:
  - pip install mkdocs==1.1
  - pip install mkdocs-material==4.6.3
  - pip install pymdown-extensions
script:
  - mkdocs build --verbose --clean
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: site
  on:
    branch: master
