language: python
install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pymdown-extensions
script:
  - mkdocs build --verbose --clean
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: site
  on:
    branch: master
