site_name: techNotes
pages:
    - Home: index.md
    - Linux: 
      - 系统: Linux/index.md
      - 软件: Linux/software.md
      - shell: shell/index.md
      - 服务器: Linux/servers.md
      - 16to18: Linux/16to18.md
    - R: 
      - 一般问题: R/index.md
      - 统计基础: R/basic.md
      - plot 作图: R/plot.md
      - ggplot 作图: R/ggplot.md
      - 案例分析: R/legend_from_zhihu.md
      - 源码安装 RMySQL: R/install-notes-for-rmysql.md
      - new sample function (v3.6.0+): R/sample.md
    - Python:
      - 一般问题: python/index.md
      - PyStan 体验: python/pystan/README.md
      - OpenCV: python/opencv.md
      - 金融数据爬虫: python/finance/README.md
      - rpy2: python/rpy2.md
      - 自建关键词索引页: python/esltag.md
    - Julia: julia/index.md
    - Tex: TeX/index.md
    - Website:
      - Website: website/index.md
      - CSS: website/css.md
      - JS: js/index.md
    - Network: 
      - 一般问题: Internet/index.md
      - 访问内网: Internet/sci-int.md
      - IPv6: Internet/ipv6.md
    - Tools:
      - Autotools: autotools/index.md
      - Emacs: Emacs/index.md
      - Vi: vi/index.md
      - Ssh: ssh/index.md
      - Git: Git/index.md
      - Phantomjs: phantomjs/index.md
      - Qt: Qt/index.md
    - Stat:
      - Probability: stats/prob.md
      - Statistic: stats/index.md
      - Scientific: scientific/index.md
      - Matrix: stats/matrix.md
    - English: English/index.md
    - Finance: finance/index.md
    - Mi: mi/index.md
    - Win: win/index.md
    - Fresh: fresh/index.md
    - Links: links/index.md
    - Misc: 
      - 小程序: misc/wx.md
      - jssdk: misc/wxjssdk.md
      - 讲座: misc/report.md
    - Others:
      - Matlab: Matlab/index.md
      - Cpp: Cpp/index.md
      - Java: java/index.md
      - SQL: SQL/index.md
      - Cuda: cuda/index.md
      - PHP: PHP/index.md

theme:
  name: 'material'
  custom_dir: 'theme'
  search:
    language: 'en, jp'
google_analytics: ['UA-85007363-6', 'auto']
copyright: 'Copyright &copy; 2017-2020 weiya'
site_author: weiya
site_description: '技术博客'
site_url: https://tech.hohoweiya.xyz
extra:
  social:
    - type: 'github'
      link: 'https://github.com/szcf-weiya'
    - type: 'book'
      link: 'https://esl.hohoweiya.xyz'
    - type: 'home'
      link: 'https://hohoweiya.xyz'
    - type: 'rss'
      link: 'https://stats.hohoweiya.xyz'
    - type: 'envelope'
      link: 'mailto:szcfweiya@gmail.com'

repo_name: 'szcf-weiya/techNotes'
repo_url: 'https://github.com/szcf-weiya/techNotes'
edit_uri: ""
extra_javascript: 
  - javascripts/baiduzhanzhang.js
  - javascripts/extra.js
  - javascripts/mathjax.js
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  # https://github.com/mkdocs/mkdocs/issues/1678
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.superfences
  - admonition
  - codehilite
  - smarty
  - sane_lists
  - meta
  - toc:
      permalink: true
